apiVersion: apps/v1
kind: Deployment
metadata:
  name: green1
spec:
  replicas: 4
  template:
    metadata:
      name: blue
      labels:
        app: green
    spec:
      containers:
        - name: cont
          image: httpd
          containerPort:
          - port: 80
  selector:
    matchLabels:
      app: green
---
apiVersion: v1
kind: Service
test
test - this is from cubensquare id

